- name: update nameserver info in resolv.conf
  hosts: all
  tasks: 
    - name: update NS info
      lineinfile:
        dest: /etc/resolv.conf
        line: 'nameserver 192.168.101.42'
      become: yes
